name: Delete many PDFs

on:
  workflow_dispatch:

jobs:
  delete-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete PDF files
        run: |
          rm -f \
          14.pdf \
          15.pdf \
          16.pdf \
          17.pdf \
          18.pdf \
          19.pdf \
          2.pdf \
          20.pdf \
          21.pdf \
          22.1.pdf \
          22.2.pdf \
          23.pdf \
          24.pdf \
          25.1.pdf \
          25.2.pdf \
          26.1.pdf \
          26.2.pdf \
          28.pdf \
          29.1.pdf \
          29.2.pdf \
          3.12.pdf \
          3.13.pdf \
          30.pdf \
          31.pdf \
          32.pdf \
          33.pdf \
          34.pdf \
          35.pdf \
          36.1.pdf \
          36.2.pdf \
          36.3.pdf \
          36.4.pdf \
          37.1.pdf \
          37.2.pdf \
          38.pdf \
          39.pdf \
          4.pdf \
          40.pdf \
          41.pdf \
          42.1.pdf \
          42.2.pdf \
          42.3.pdf \
          43.pdf \
          44.pdf \
          45.pdf \
          46.pdf \
          47.pdf \
          48.pdf \
          5.pdf \
          50.1.pdf \
          51.2.pdf \
          52.pdf \
          53.1.pdf \
          53.2.pdf \
          54.pdf \
          55.pdf \
          56.pdf \
          57.pdf \
          58.pdf \
          59.1.pdf \
          59.3.pdf \
          59.5.pdf \
          6.pdf \
          61.1.pdf \
          61.2.pdf \
          62.pdf \
          63.1.pdf \
          63.2.pdf \
          64.11deuxième.pdf \
          64.11première.pdf \
          65.pdf \
          66.pdf \
          67.pdf \
          68.1.pdf \
          68.2.pdf \
          69deuxième.pdf \
          69première.pdf \
          7.pdf \
          70premièremoitié.pdf \
          70secondemoutié.pdf \
          71.pdf \
          72.pdf \
          73.pdf \
          74.pdf \
          75.1.pdf \
          75.2.pdf \
          75.3.pdf \
          77.1.pdf \
          77.3.pdf \
          78.pdf \
          79.pdf \
          8.pdf \
          80.pdf \
          81.pdf \
          82.1.pdf \
          82.2.pdf \
          82.3.pdf \
          83.pdf \
          84.1.pdf \
          84.2.pdf \
          85.pdf \
          86.pdf \
          87.pdf \
          88.1.pdf \
          88.2.pdf \
          89.pdf \
          9.1.pdf \
          9.2.pdf \
          9.3.pdf

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -u
          git commit -m "Remove bulk PDF files"
          git push
