# name: Deploy to Supabase

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Install Supabase CLI
#         run: |
#           curl -fsSL https://cli.supabase.com/install.sh | sh

#       - name: Locate Supabase CLI
#         run: |
#           find $HOME -type f -name supabase || true

#       - name: Check Supabase CLI version (absolute path)
#         run: |
#           $HOME/.supabase/bin/supabase --version || true
