name: OCR PDF -> CSV

on:
  workflow_dispatch:
    inputs:
      pdf_url:
        description: "URL du PDF Ã  traiter"
        required: true
        default: "https://yannkerherve.github.io/secretaires/1.pdf"

jobs:
  ocr_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Create output directory
        run: mkdir -p ocr_csv

      - name: Run OCR
        run: |
          set -o pipefail
          node ocr.js "${{ github.event.inputs.pdf_url }}" | tee /dev/stdout

      - name: Upload result CSV
        uses: actions/upload-artifact@v4
        with:
          name: csv-output
          path: ocr_csv/*.csv
